#+TITLE: Aula 1 de Coq
#+AUTHOR: Rafael Castro
#+EMAIL: rafaelcgs10@gmail.com
#+startup: beamer
#+LaTeX_CLASS: beamer
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css"/>
#+LATEX_HEADER: \usepackage{graphicx, hyperref, udesc, url}
#+OPTIONS:   H:2 toc:nil
#+DATE: 03/05/2018

#+LANGUAGE: pt

* Introducao

** Provadores Automáticos
  - Entre com uma proposição, aperte um botão e veja a resposta.
  - Fazem todo o trabalho da prova. Humanos não são necessários.
  - Limitados a domínios específicos.
  - São procedimentos de decisão.
  - Fornecem um formalismo para especificar a proposição, mas não para a sua prova. Fornecem uma valoração caso falso.
** Assistentes de Provas
  - São provadores semi-automáticos.
  - Uso com domínio menos restrito: podem falar sobre diversas lógicas, teorias e até mesmo programas.
  - Podem utilizar provadores automáticos, mas ainda necessitam do humano.
  - Fornecem um formalismo para representar a prova. /Lembra/ as regras da Dedução.

** Como Assistentes de provas assistem?
 - O núcleo de um assistente de provas é um verificador, que verifica a consistência lógica da prova. 
 - Fornecem de maneira interativa de visualizar as informações sobre o estado atual da prova.
 - Ajudam a encontrar teoremas e lemas para o progresso da prova.
 - Permitem implementar métodos não-deterministas para auxiliar a prova. 

** Qual assistente utilizar?
 - Existem diversos assistentes, cada um baseado numa teoria matemática e com as suas peculiaridades:
   Agda, Isabelle, HOL, Minlog, Coq...
 - Iremmos utilizar Coq! Mas por que?
   1 - É o que eu sei algo;
   2 - Existe desde 1984;
   3 - Há vários livros.
   4 - Suporte para ordem superior, tipos dependentes, automação e extração de código.
   
** Como aprender Coq?

* Baby's First Steps

** Como utilizar o assistente de provas?
 - CoqIDE = Bom lugar para começar sem perder o foco. Tem os recursos básicos. 
 - Emacs + ProofGeneral + Company-coq = 
